version: 2
jobs:
  build:
    working_directory: ~/heaven

    # Primary container image where all commands run

    docker:
      - image: circleci/ruby:2.3.4
        environment:
          RAILS_ENV: test
      - image: redis:5.0

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - heaven-{{ checksum "Gemfile.lock" }}
            - heaven-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: heaven-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:test:prepare

      - run:
          name: RSpec
          command: bundle exec rspec spec

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
